### PR TITLE
Add typescript definition

### PR DESCRIPTION
**Pull request by tobilen**
Adds a definition file for typescript projects with the same typing as is provided in the flow file

### CODE REVIEW

**Comment by cdpautsch** [comment]
This would be great. I'm getting an error about it when I import the module.

**Comment by tobilen** [comment]
last time poking @erikras helped 😛

**Comment by Toyinster** [comment]
+1

**Comment by tobilen** [comment]
@erikras anything missing for a merge?

**Comment by tobilen** [comment]
*bump*

**Comment by tobilen** [comment]
no longer up to date with the most recent type changes. i won't bother with a new PR 😛

**Pull request closed without merging**
